services:

  # django rest
  django_backend:
    build: .
    ports:
      - "3333:8000"
    container_name: django_backend
    volumes:
      - static_volume:/bot_backend/static

  # telegram bot
  client:
    build: ../bot_front_new
    ports:
      - "4000:8001"

  # memes downloder
  updater:
    build: ../service
    ports:
      - "5000:8001"

  # nginx
  web_nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker_nginx/
    container_name: dj_nginx
    ports:
      - "8000:80"
    volumes:
      - static_volume:/bot_backend/static
    environment:
      - NGINX_PORT=80
    depends_on:
      - django_backend


volumes:
  static_volume:
  media_volume: